import React from "react";
import { Route } from "react-router-dom";
import { setupServer } from "msw/node";
import mockYieldXPortfolio from "__mocks__/models/mockYieldXPortfolio";
import userEvent from "@testing-library/user-event";
import { render, screen } from "test/utils";
import { client } from "providers/graphql";
import mockInpaasPortfolioRequests from "mock-requests/graphql/mockInpaasPortfolioRequests";
import PortfolioDisplay from "./PortfolioDisplay";

export const mockAssets = [
  {
    allocation: {
      country: {
        no: 0.104,
        de: 0.3458,
        other: 1.0708,
        fi: 0.0986,
        ch: 0.0496,
        dk: 0.0945,
        lu: 1.348,
        bm: 0.333,
        it: 0.6848,
        fr: 0.1572,
        es: 0.0007,
        ky: 0.791,
        se: 0.1608,
        at: 0.1001,
        au: 0.4262,
        sn: 0.1015,
        gb: 1.4508,
        ie: 0.7373,
        nl: 1.5839,
        ca: 4.7017,
        us: 83.2512
      },
      currency: {
        aud: 0.028,
        other: 0.196,
        eur: 0.0715,
        gbp: 0.0459,
        cad: 0.0945,
        usd: 98.5529
      },
      debtType: null,
      maturity: {
        fiveToTenYears: 2.1135,
        greaterThanThirtyYears: null,
        lessThanOneYear: 5.2378,
        oneToThreeYears: 30.4817,
        other: 0.0006,
        tenToTwentyYears: 0.0659,
        threeToFiveYears: 59.6918,
        twentyToThirtyYears: null,
        __typename: "MaturityAllocation"
      },
      rating: {
        a: null,
        aa: null,
        aaa: null,
        b: 29.9979,
        bb: 50.5137,
        bbb: 2.7644,
        c: 0.7443,
        cc: 0.3034,
        ccc: 12.676,
        d: 0.0549,
        nr: 0.5367,
        __typename: "RatingAllocation2"
      },
      region: {
        africaExNorthAfrica: 0.0093,
        asiaPacificExJapan: 0.6289,
        emergingMarketsAsia: 0.4435,
        emergingMarketsEurope: null,
        europeExUnitedKingdom: 5.6814,
        japan: 0.0261,
        latinAmerica: null,
        middleEastNorthAfrica: null,
        northAmericaExUnitedStates: 6.3117,
        other: 0.4984,
        unitedKingdom: 1.5461,
        unitedStates: 83.8434,
        __typename: "RegionAllocation"
      },
      sector: null,
      __typename: "Allocation7"
    },
    analytics: {
      convexity: null,
      creditBeta: null,
      currentYield: null,
      date: "2020-11-02",
      defaultAdjustedYield: null,
      distributionYield: 5.802867,
      dividendYield: null,
      duration: null,
      effectiveDuration: null,
      gSpread: null,
      optionAdjustedSpread: null,
      recoveryRate: null,
      secYield: 5.374,
      source: "Lipper",
      spreadDuration: null,
      standaloneRisk: null,
      yearsToMaturity: null,
      yield: 5.08,
      yieldToCall: null,
      yieldToMaturity: null,
      yieldToWorst: null,
      zSpread: null,
      __typename: "Analytics"
    },
    assetSubtype: "EXCHANGE_TRADED_FUNDS",
    assetType: "FUND",
    bond: null,
    country: null,
    createdAt: "2019-11-18T00:30:12.474548Z",
    createdBy: null,
    currency: "USD",
    description:
      "The Fund seeks to track the performance of index that tracks the US high yield short term corporate bond market. The Index is designed to measure the performance of short-term publicly issued US dollar denominated high yield corporate bonds.",
    displayId: null,
    equity: null,
    fund: {
      allocation: {
        asset: {
          cash: 1.2352,
          equity: 0.033,
          fixedIncome: 98.6202,
          other: 0.1116,
          __typename: "AssetAllocation"
        },
        currency: {
          aud: 0.028,
          other: 0.196,
          eur: 0.0715,
          gbp: 0.0459,
          cad: 0.0945,
          usd: 98.5529
        },
        equityCountry: null,
        equityRegion: null,
        fixedIncomeCountry: {
          no: 0.104,
          de: 0.3458,
          other: 1.0708,
          fi: 0.0986,
          ch: 0.0496,
          dk: 0.0945,
          lu: 1.348,
          bm: 0.333,
          it: 0.6848,
          fr: 0.1572,
          es: 0.0007,
          ky: 0.791,
          se: 0.1608,
          at: 0.1001,
          au: 0.4262,
          sn: 0.1015,
          gb: 1.4508,
          ie: 0.7373,
          nl: 1.5839,
          ca: 4.7017,
          us: 83.2512
        },
        fixedIncomeRegion: {
          africaExNorthAfrica: null,
          asiaPacificExJapan: 0.5277,
          emergingMarketsAsia: 0.4435,
          emergingMarketsEurope: null,
          europeExUnitedKingdom: 5.5487,
          japan: null,
          latinAmerica: null,
          middleEastNorthAfrica: null,
          northAmericaExUnitedStates: 6.1076,
          other: 0.2618,
          unitedKingdom: 1.4508,
          unitedStates: 83.2512,
          __typename: "RegionAllocation"
        },
        gicsSubIndustry: null,
        trbcIndustry: null,
        __typename: "FundAllocation"
      },
      apexSupport: null,
      assetStatus: "Active",
      benchmark: "Bloomberg Barclays U.S. Corporate High Yield TR",
      classification: "High Yield",
      distributions: {
        capitalGain: null,
        foreignTaxCredit: null,
        income: {
          aggregateAccrual: null,
          exemptIncome: null,
          incomeDividend: {
            accountingDate: null,
            exDate: "2020-10-01",
            exValue: 0.124943,
            paymentDate: "2020-10-07",
            recordDate: null,
            reinvestmentDate: "2020-10-01",
            reinvestmentType: "Nav",
            reinvestmentValue: 25.756495,
            taxableInterestIncome: null,
            __typename: "FundDistribution"
          },
          interestIncome: null,
          nonQualifiedIncomeDividend: {
            accountingDate: null,
            exDate: "2019-12-20",
            exValue: 0.117925,
            paymentDate: "2019-12-27",
            recordDate: null,
            reinvestmentDate: "2019-12-20",
            reinvestmentType: "Nav",
            reinvestmentValue: 26.840292,
            taxableInterestIncome: null,
            __typename: "FundDistribution"
          },
          qualifiedIncomeDividend: {
            accountingDate: null,
            exDate: "2019-07-01",
            exValue: 0.342778,
            paymentDate: "2019-07-08",
            recordDate: null,
            reinvestmentDate: "2019-07-01",
            reinvestmentType: "Nav",
            reinvestmentValue: 27.113158,
            taxableInterestIncome: null,
            __typename: "FundDistribution"
          },
          __typename: "IncomeDistributions"
        },
        repaymentCategory: null,
        __typename: "FundDistributions"
      },
      fees: {
        backLoad: null,
        frontLoad: null,
        fundExpenseRatio: 0.4,
        managementFee: 0.4,
        marketing12b1Fee: null,
        performanceFee: null,
        __typename: "Fees"
      },
      focus: {
        assetClassFocus: "Bond",
        geoFocus: "United States of America",
        __typename: "Focus"
      },
      fundType: "Exchange Traded Funds",
      inceptionDate: "2012-03-14",
      institutional: false,
      managementCompany: "SSgA Funds Management Inc",
      midPrice: 25.89,
      netAssetValuePerShare: 25.837504,
      netAssets: 3312367960.34,
      netAssetsDate: "2020-10-30",
      priceDate: "2020-10-30",
      regulatoryStructure: null,
      replicationStrategy: "Optimized",
      scores: {
        consistentReturn: {
          fiveYear: 5,
          overall: 5,
          tenYear: null,
          threeYear: 5,
          __typename: "Score"
        },
        expense: {
          fiveYear: 5,
          overall: 5,
          tenYear: null,
          threeYear: 5,
          __typename: "Score"
        },
        preservation: {
          fiveYear: 2,
          overall: 2,
          tenYear: null,
          threeYear: 2,
          __typename: "Score"
        },
        taxEfficiency: {
          fiveYear: 1,
          overall: 1,
          tenYear: null,
          threeYear: 1,
          __typename: "Score"
        },
        totalReturn: {
          fiveYear: 5,
          overall: 5,
          tenYear: null,
          threeYear: 5,
          __typename: "Score"
        },
        __typename: "Scores6"
      },
      tradeLotSize: 0,
      yields: {
        dailySecYield: 5.08,
        dailySecYieldDate: "2020-11-03",
        distributionYield: 5.3920224,
        dividendYield: null,
        lipperDistributionYield: 5.802867,
        projectedYield: 5.3443799,
        secYield: 5.374,
        simpleYieldBegin: 5.439643,
        simpleYieldEnd: 5.6294641,
        thirtyDayYield: 5.373545,
        trailingTwelveMonthYield: 5.6575666,
        __typename: "FundYields"
      },
      __typename: "Fund4"
    },
    id: "c7283330-e6e8-43ca-9457-d7ec6ce2656e",
    identifiers: {
      apex: "78468R408",
      bbGlobal: null,
      cik: null,
      cins: null,
      cusip: "78468R408",
      isin: "US78468R4083",
      primaryTicker: null,
      refinitivAssetId: null,
      refinitivIssuePermId: null,
      refinitivLipperId: "40197411",
      refinitivLipperParentId: "36403937",
      refinitivLipperPermId: null,
      sedol: "B7N0HC6",
      valoren: null,
      __typename: "Identifiers"
    },
    legalEntity: null,
    liquid: null,
    market: "USA",
    metadata: null,
    name: "SPDR Bbg Barclays Short Term High Yield Bond ETF",
    price: 25.89,
    priceDate: "2020-10-30",
    priceQuotes: null,
    primaryExchange: "Arca",
    primaryExchangeMic: null,
    scores: {
      attractiveness: 1,
      credit: 3,
      efficiency: 3.4,
      liquidity: 3,
      risk: 7.684036994475988,
      timestamp: null,
      __typename: "RoverScores"
    },
    ticker: "SJNK",
    unit: null,
    universes: {
      custom: null,
      general: true,
      liquid: true,
      search: true,
      timestamp: "2020-11-03T05:28:39.297357Z",
      __typename: "Universes"
    },
    updatedAt: "2020-11-03T05:28:39.297338Z",
    updatedBy: "bry",
    __typename: "Asset5"
  },
  {
    allocation: {
      country: { other: 0.0008, us: 99.4206 },
      currency: { other: 6.3406, cad: 0, usd: 93.574 },
      debtType: null,
      maturity: {
        fiveToTenYears: 2.9235,
        greaterThanThirtyYears: 0.1364,
        lessThanOneYear: 0.0009,
        oneToThreeYears: 0.0086,
        other: 17.7069,
        tenToTwentyYears: 8.9375,
        threeToFiveYears: 0.0552,
        twentyToThirtyYears: 69.6525,
        __typename: "MaturityAllocation"
      },
      rating: {
        a: null,
        aa: 99.4197,
        aaa: 0.0009,
        b: null,
        bb: null,
        bbb: null,
        c: null,
        cc: null,
        ccc: null,
        d: null,
        nr: 0.0008,
        __typename: "RatingAllocation2"
      },
      region: {
        africaExNorthAfrica: null,
        asiaPacificExJapan: 0.5055,
        emergingMarketsAsia: null,
        emergingMarketsEurope: null,
        europeExUnitedKingdom: 1.247,
        japan: 0.0586,
        latinAmerica: null,
        middleEastNorthAfrica: null,
        northAmericaExUnitedStates: 1.4784,
        other: 6.1464,
        unitedKingdom: 0.6003,
        unitedStates: 89.8784,
        __typename: "RegionAllocation"
      },
      sector: null,
      __typename: "Allocation7"
    },
    analytics: {
      convexity: null,
      creditBeta: null,
      currentYield: null,
      date: "2020-11-02",
      defaultAdjustedYield: null,
      distributionYield: 2.0807366,
      dividendYield: null,
      duration: null,
      effectiveDuration: null,
      gSpread: null,
      optionAdjustedSpread: null,
      recoveryRate: null,
      secYield: 1.58,
      source: "Lipper",
      spreadDuration: null,
      standaloneRisk: null,
      yearsToMaturity: null,
      yield: 1.55,
      yieldToCall: null,
      yieldToMaturity: null,
      yieldToWorst: null,
      zSpread: null,
      __typename: "Analytics"
    },
    assetSubtype: "EXCHANGE_TRADED_FUNDS",
    assetType: "FUND",
    bond: null,
    country: null,
    createdAt: "2019-11-17T23:31:47.294322Z",
    createdBy: null,
    currency: "USD",
    description:
      "The Fund seeks investment results that correspond to the investment grade agency mortgage-backed securities sector of the U.S. as defined by the Barclays Capital U.S. MBS Fixed-Rate Index The Index includes securities issued by GNMA, FHLMC, and FNMA that have 30-, 20-, 15-year and balloon securities.",
    displayId: null,
    equity: null,
    fund: {
      allocation: {
        asset: {
          cash: -12.9869,
          equity: null,
          fixedIncome: 112.3403,
          other: 0.6468,
          __typename: "AssetAllocation"
        },
        currency: { other: 6.3406, cad: 0, usd: 93.574 },
        equityCountry: null,
        equityRegion: null,
        fixedIncomeCountry: { other: 0.0008, us: 99.4206 },
        fixedIncomeRegion: {
          africaExNorthAfrica: null,
          asiaPacificExJapan: null,
          emergingMarketsAsia: null,
          emergingMarketsEurope: null,
          europeExUnitedKingdom: null,
          japan: null,
          latinAmerica: null,
          middleEastNorthAfrica: null,
          northAmericaExUnitedStates: null,
          other: 0.0008,
          unitedKingdom: null,
          unitedStates: 99.4206,
          __typename: "RegionAllocation"
        },
        gicsSubIndustry: null,
        trbcIndustry: null,
        __typename: "FundAllocation"
      },
      apexSupport: null,
      assetStatus: "Active",
      benchmark: "Bloomberg Barclays U.S. Aggregate Bond TR",
      classification: "Mortgages",
      distributions: {
        capitalGain: {
          capitalGain: null,
          collectibles: null,
          longTermCapitalGain: {
            accountingDate: null,
            exDate: "2016-12-01",
            exValue: 0.237991,
            paymentDate: "2016-12-07",
            recordDate: null,
            reinvestmentDate: "2016-12-01",
            reinvestmentType: "Nav",
            reinvestmentValue: 106.68,
            taxableInterestIncome: null,
            __typename: "FundDistribution"
          },
          mediumTermCapitalGain: null,
          nonQualifiedShortTermCapitalGain: {
            accountingDate: null,
            exDate: "2015-12-01",
            exValue: 0.553801,
            paymentDate: "2015-12-07",
            recordDate: null,
            reinvestmentDate: "2015-12-01",
            reinvestmentType: "Nav",
            reinvestmentValue: 108.49,
            taxableInterestIncome: null,
            __typename: "FundDistribution"
          },
          qualifiedShortTermCapitalGain: null,
          returnOfCapital: {
            accountingDate: null,
            exDate: "2018-02-01",
            exValue: 0.03774,
            paymentDate: "2018-02-07",
            recordDate: null,
            reinvestmentDate: "2018-02-01",
            reinvestmentType: "Nav",
            reinvestmentValue: 104.8,
            taxableInterestIncome: null,
            __typename: "FundDistribution"
          },
          shortTermCapitalGain: {
            accountingDate: null,
            exDate: "2010-12-01",
            exValue: 2.499641,
            paymentDate: "2010-12-07",
            recordDate: null,
            reinvestmentDate: "2010-12-01",
            reinvestmentType: "Nav",
            reinvestmentValue: 105.8497,
            taxableInterestIncome: null,
            __typename: "FundDistribution"
          },
          superLongTermCapitalGain: null,
          __typename: "CapitalGainDistributions"
        },
        foreignTaxCredit: null,
        income: {
          aggregateAccrual: null,
          exemptIncome: null,
          incomeDividend: {
            accountingDate: null,
            exDate: "2020-10-01",
            exValue: 0.191133,
            paymentDate: "2020-10-07",
            recordDate: null,
            reinvestmentDate: "2020-10-01",
            reinvestmentType: "Nav",
            reinvestmentValue: 110.29,
            taxableInterestIncome: null,
            __typename: "FundDistribution"
          },
          interestIncome: null,
          nonQualifiedIncomeDividend: {
            accountingDate: null,
            exDate: "2018-12-18",
            exValue: 0.083667,
            paymentDate: "2018-12-24",
            recordDate: null,
            reinvestmentDate: "2018-12-18",
            reinvestmentType: "Nav",
            reinvestmentValue: 103.99,
            taxableInterestIncome: null,
            __typename: "FundDistribution"
          },
          qualifiedIncomeDividend: null,
          __typename: "IncomeDistributions"
        },
        repaymentCategory: null,
        __typename: "FundDistributions"
      },
      fees: {
        backLoad: null,
        frontLoad: null,
        fundExpenseRatio: 0.06,
        managementFee: 0.06,
        marketing12b1Fee: null,
        performanceFee: null,
        __typename: "Fees"
      },
      focus: {
        assetClassFocus: "Bond",
        geoFocus: "United States of America",
        __typename: "Focus"
      },
      fundType: "Exchange Traded Funds",
      inceptionDate: "2007-03-13",
      institutional: false,
      managementCompany: "BlackRock Fund Advisors",
      midPrice: 110.29,
      netAssetValuePerShare: 110.23,
      netAssets: 23832284425.22,
      netAssetsDate: "2020-10-30",
      priceDate: "2020-10-30",
      regulatoryStructure: null,
      replicationStrategy: "Optimized",
      scores: {
        consistentReturn: {
          fiveYear: 3,
          overall: 3,
          tenYear: 2,
          threeYear: 4,
          __typename: "Score"
        },
        expense: {
          fiveYear: 5,
          overall: 5,
          tenYear: 5,
          threeYear: 5,
          __typename: "Score"
        },
        preservation: {
          fiveYear: 5,
          overall: 5,
          tenYear: 5,
          threeYear: 5,
          __typename: "Score"
        },
        taxEfficiency: {
          fiveYear: 4,
          overall: 4,
          tenYear: 4,
          threeYear: 4,
          __typename: "Score"
        },
        totalReturn: {
          fiveYear: 3,
          overall: 3,
          tenYear: 3,
          threeYear: 4,
          __typename: "Score"
        },
        __typename: "Scores6"
      },
      tradeLotSize: 0,
      yields: {
        dailySecYield: 1.55,
        dailySecYieldDate: "2020-11-03",
        distributionYield: 2.0798113,
        dividendYield: null,
        lipperDistributionYield: 2.0807366,
        projectedYield: 2.2077975,
        secYield: 1.58,
        simpleYieldBegin: 2.2411976,
        simpleYieldEnd: 2.1968738,
        thirtyDayYield: 1.58,
        trailingTwelveMonthYield: 2.2584278,
        __typename: "FundYields"
      },
      __typename: "Fund4"
    },
    id: "a5dcf04f-f831-4fd5-a692-41c75f1bf62f",
    identifiers: {
      apex: "464288588",
      bbGlobal: null,
      cik: null,
      cins: null,
      cusip: "464288588",
      isin: "US4642885887",
      primaryTicker: null,
      refinitivAssetId: null,
      refinitivIssuePermId: null,
      refinitivLipperId: "40111259",
      refinitivLipperParentId: "30091864",
      refinitivLipperPermId: null,
      sedol: "B1VKHR1",
      valoren: null,
      __typename: "Identifiers"
    },
    legalEntity: null,
    liquid: null,
    market: "USA",
    metadata: null,
    name: "iShares MBS ETF",
    price: 110.29,
    priceDate: "2020-10-30",
    priceQuotes: null,
    primaryExchange: "NASDAQ",
    primaryExchangeMic: null,
    scores: {
      attractiveness: 1,
      credit: 3,
      efficiency: 4.6,
      liquidity: 3,
      risk: 2.256650724733227,
      timestamp: null,
      __typename: "RoverScores"
    },
    ticker: "MBB",
    unit: null,
    universes: {
      custom: null,
      general: true,
      liquid: true,
      search: true,
      timestamp: "2020-11-03T05:25:52.903563Z",
      __typename: "Universes"
    },
    updatedAt: "2020-11-03T05:25:52.903519Z",
    updatedBy: "bry",
    __typename: "Asset5"
  },
  {
    allocation: {
      country: {
        other: 30.4049,
        lu: 3.1124,
        gb: 0.4607,
        ie: 0.5505,
        fr: 1.204,
        nl: 1.7042,
        ca: 2.2614,
        us: 53.5814
      },
      currency: { other: 12.9516, gbp: 0.9333, cad: 1.224, usd: 89.7313 },
      debtType: null,
      maturity: {
        fiveToTenYears: 34.2163,
        greaterThanThirtyYears: null,
        lessThanOneYear: 0.767,
        oneToThreeYears: 8.5735,
        other: null,
        tenToTwentyYears: 0.1663,
        threeToFiveYears: 49.5564,
        twentyToThirtyYears: null,
        __typename: "MaturityAllocation"
      },
      rating: {
        a: null,
        aa: null,
        aaa: null,
        b: 6.5659,
        bb: 1.455,
        bbb: null,
        c: null,
        cc: 0.0972,
        ccc: 1.3323,
        d: null,
        nr: 83.829,
        __typename: "RatingAllocation2"
      },
      region: {
        africaExNorthAfrica: null,
        asiaPacificExJapan: null,
        emergingMarketsAsia: null,
        emergingMarketsEurope: null,
        europeExUnitedKingdom: 6.5711,
        japan: null,
        latinAmerica: null,
        middleEastNorthAfrica: null,
        northAmericaExUnitedStates: 3.1535,
        other: 32.2596,
        unitedKingdom: 0.4607,
        unitedStates: 62.3954,
        __typename: "RegionAllocation"
      },
      sector: null,
      __typename: "Allocation7"
    },
    analytics: {
      convexity: null,
      creditBeta: null,
      currentYield: null,
      date: "2020-11-02",
      defaultAdjustedYield: null,
      distributionYield: 5.1431304,
      dividendYield: null,
      duration: null,
      effectiveDuration: null,
      gSpread: null,
      optionAdjustedSpread: null,
      recoveryRate: null,
      secYield: 5.008,
      source: "Lipper",
      spreadDuration: null,
      standaloneRisk: null,
      yearsToMaturity: null,
      yield: 4.77,
      yieldToCall: null,
      yieldToMaturity: null,
      yieldToWorst: null,
      zSpread: null,
      __typename: "Analytics"
    },
    assetSubtype: "EXCHANGE_TRADED_FUNDS",
    assetType: "FUND",
    bond: null,
    country: null,
    createdAt: "2019-11-22T09:35:58.207597Z",
    createdBy: null,
    currency: "USD",
    description:
      "The Fund seeks to provide current income consistent with the preservation of capital. The Portfolio seeks to outperform the Markit iBoxx USD Leveraged Loan Index and the S&P/LSTA US Leveraged Loan 100 Index by normally investing at least 80% of its net assets (plus any borrowings for investment purposes) in Senior Loans.",
    displayId: null,
    equity: null,
    fund: {
      allocation: {
        asset: {
          cash: -2.3568,
          equity: null,
          fixedIncome: 100.7778,
          other: 1.579,
          __typename: "AssetAllocation"
        },
        currency: { other: 12.9516, gbp: 0.9333, cad: 1.224, usd: 89.7313 },
        equityCountry: null,
        equityRegion: null,
        fixedIncomeCountry: {
          other: 30.4049,
          lu: 3.1124,
          gb: 0.4607,
          ie: 0.5505,
          fr: 1.204,
          nl: 1.7042,
          ca: 2.2614,
          us: 53.5814
        },
        fixedIncomeRegion: {
          africaExNorthAfrica: null,
          asiaPacificExJapan: null,
          emergingMarketsAsia: null,
          emergingMarketsEurope: null,
          europeExUnitedKingdom: 6.5711,
          japan: null,
          latinAmerica: null,
          middleEastNorthAfrica: null,
          northAmericaExUnitedStates: 2.2614,
          other: 30.4049,
          unitedKingdom: 0.4607,
          unitedStates: 53.5814,
          __typename: "RegionAllocation"
        },
        gicsSubIndustry: null,
        trbcIndustry: null,
        __typename: "FundAllocation"
      },
      apexSupport: null,
      assetStatus: "Active",
      benchmark: "Markit iBoxx USD Liquid Investment Grade TR",
      classification: "Loan Participation Funds",
      distributions: {
        capitalGain: null,
        foreignTaxCredit: null,
        income: {
          aggregateAccrual: null,
          exemptIncome: null,
          incomeDividend: {
            accountingDate: null,
            exDate: "2020-10-01",
            exValue: 0.19,
            paymentDate: "2020-10-07",
            recordDate: null,
            reinvestmentDate: "2020-10-01",
            reinvestmentType: "Nav",
            reinvestmentValue: 44.482514,
            taxableInterestIncome: null,
            __typename: "FundDistribution"
          },
          interestIncome: null,
          nonQualifiedIncomeDividend: {
            accountingDate: null,
            exDate: "2019-12-20",
            exValue: 0.17,
            paymentDate: "2019-12-27",
            recordDate: null,
            reinvestmentDate: "2019-12-20",
            reinvestmentType: "Nav",
            reinvestmentValue: 46.465386,
            taxableInterestIncome: null,
            __typename: "FundDistribution"
          },
          qualifiedIncomeDividend: null,
          __typename: "IncomeDistributions"
        },
        repaymentCategory: null,
        __typename: "FundDistributions"
      },
      fees: {
        backLoad: null,
        frontLoad: null,
        fundExpenseRatio: 0.7,
        managementFee: 0.7,
        marketing12b1Fee: null,
        performanceFee: null,
        __typename: "Fees"
      },
      focus: {
        assetClassFocus: "Bond",
        geoFocus: "United States of America",
        __typename: "Focus"
      },
      fundType: "Exchange Traded Funds",
      inceptionDate: "2013-04-03",
      institutional: false,
      managementCompany: "SSgA Funds Management Inc",
      midPrice: 44.26,
      netAssetValuePerShare: 44.330978,
      netAssets: 1686793700.51,
      netAssetsDate: "2020-10-30",
      priceDate: "2020-10-30",
      regulatoryStructure: null,
      replicationStrategy: null,
      scores: {
        consistentReturn: {
          fiveYear: 4,
          overall: 5,
          tenYear: null,
          threeYear: 5,
          __typename: "Score"
        },
        expense: {
          fiveYear: 4,
          overall: 4,
          tenYear: null,
          threeYear: 4,
          __typename: "Score"
        },
        preservation: {
          fiveYear: 2,
          overall: 2,
          tenYear: null,
          threeYear: 2,
          __typename: "Score"
        },
        taxEfficiency: {
          fiveYear: 2,
          overall: 2,
          tenYear: null,
          threeYear: 1,
          __typename: "Score"
        },
        totalReturn: {
          fiveYear: 4,
          overall: 5,
          tenYear: null,
          threeYear: 5,
          __typename: "Score"
        },
        __typename: "Scores6"
      },
      tradeLotSize: 0,
      yields: {
        dailySecYield: 4.77,
        dailySecYieldDate: "2020-11-03",
        distributionYield: 5.1431304,
        dividendYield: null,
        lipperDistributionYield: 5.1431304,
        projectedYield: 4.8039021,
        secYield: 5.008,
        simpleYieldBegin: 4.8987205,
        simpleYieldEnd: 5.0529,
        thirtyDayYield: 5.007689,
        trailingTwelveMonthYield: 5.0529,
        __typename: "FundYields"
      },
      __typename: "Fund4"
    },
    id: "4eacb809-f4eb-41c6-9716-44f3a3ea3926",
    identifiers: {
      apex: "78467V608",
      bbGlobal: null,
      cik: null,
      cins: null,
      cusip: "78467V608",
      isin: "US78467V6083",
      primaryTicker: null,
      refinitivAssetId: null,
      refinitivIssuePermId: null,
      refinitivLipperId: "40203019",
      refinitivLipperParentId: "36499133",
      refinitivLipperPermId: null,
      sedol: null,
      valoren: null,
      __typename: "Identifiers"
    },
    legalEntity: null,
    liquid: null,
    market: "USA",
    metadata: null,
    name: "SPDR Blackstone/GSO Senior Loan ETF",
    price: 44.26,
    priceDate: "2020-10-30",
    priceQuotes: null,
    primaryExchange: "Arca",
    primaryExchangeMic: null,
    scores: {
      attractiveness: 1,
      credit: 3,
      efficiency: 3.2,
      liquidity: 3,
      risk: 7.351421492235922,
      timestamp: null,
      __typename: "RoverScores"
    },
    ticker: "SRLN",
    unit: null,
    universes: {
      custom: null,
      general: true,
      liquid: true,
      search: true,
      timestamp: "2020-11-03T05:29:27.528166Z",
      __typename: "Universes"
    },
    updatedAt: "2020-11-03T05:29:27.528151Z",
    updatedBy: "bry",
    __typename: "Asset5"
  },
  {
    allocation: {
      country: {
        other: 17.866400000000002,
        hk: 2.9699,
        lu: 5.0235,
        bm: 0.6566,
        ua: 0.387,
        br: 1.768,
        id: 0.9655,
        sn: 2.1244,
        gb: 4.4354,
        ie: 2.4469,
        ca: 1.9396,
        us: 2.5413,
        il: 0.6789,
        ae: 1.78,
        in: 3.2517,
        kr: 0.3785,
        za: 1.9079,
        cl: 1.0321,
        cn: 5.6755,
        mx: 7.3626,
        my: 0.0662,
        co: 1.4905,
        es: 0.3622,
        ky: 9.2731,
        ar: 4.1157,
        at: 0.5012,
        pe: 1.5601,
        vn: 0.097,
        ng: 0.4662,
        nl: 8.56,
        tr: 9.2559
      },
      currency: { usd: 101.0375 },
      debtType: null,
      maturity: {
        fiveToTenYears: 28.3351,
        greaterThanThirtyYears: 0.7301,
        lessThanOneYear: null,
        oneToThreeYears: 33.3424,
        other: 4.2762,
        tenToTwentyYears: 1.9481,
        threeToFiveYears: 28.9012,
        twentyToThirtyYears: 3.4065,
        __typename: "MaturityAllocation"
      },
      rating: {
        a: null,
        aa: null,
        aaa: null,
        b: 30.4304,
        bb: 54.9764,
        bbb: 6.8856,
        c: 0.4877,
        cc: 0.4371,
        ccc: 6.9406,
        d: 0.3189,
        nr: 0.4632,
        __typename: "RatingAllocation2"
      },
      region: {
        africaExNorthAfrica: 5.0182,
        asiaPacificExJapan: 5.0943,
        emergingMarketsAsia: 14.9437,
        emergingMarketsEurope: null,
        europeExUnitedKingdom: 17.7535,
        japan: null,
        latinAmerica: 19.4948,
        middleEastNorthAfrica: 4.7977,
        northAmericaExUnitedStates: 15.6342,
        other: 11.324499999999999,
        unitedKingdom: 4.4354,
        unitedStates: 2.5413,
        __typename: "RegionAllocation"
      },
      sector: null,
      __typename: "Allocation7"
    },
    analytics: {
      convexity: null,
      creditBeta: null,
      currentYield: null,
      date: "2020-11-02",
      defaultAdjustedYield: null,
      distributionYield: 5.7418176,
      dividendYield: null,
      duration: null,
      effectiveDuration: null,
      gSpread: null,
      optionAdjustedSpread: null,
      recoveryRate: null,
      secYield: 6.04,
      source: "Lipper",
      spreadDuration: null,
      standaloneRisk: null,
      yearsToMaturity: null,
      yield: 6.04,
      yieldToCall: null,
      yieldToMaturity: null,
      yieldToWorst: null,
      zSpread: null,
      __typename: "Analytics"
    },
    assetSubtype: "EXCHANGE_TRADED_FUNDS",
    assetType: "FUND",
    bond: null,
    country: null,
    createdAt: "2019-11-18T00:32:07.672267Z",
    createdBy: null,
    currency: "USD",
    description:
      "The Fund seeks to replicate the price and yield performances of the BofA Merrill Lynch High Yield US Emerging Markets Liquid Corporate Plus Index. The Index comprised of U.S. dollar denominated bonds issued by non-sovereign emerging market issuers that are rated BB1 or lower.",
    displayId: null,
    equity: null,
    fund: {
      allocation: {
        asset: {
          cash: -1.0375,
          equity: 0.0976,
          fixedIncome: 100.9399,
          other: null,
          __typename: "AssetAllocation"
        },
        currency: { usd: 101.0375 },
        equityCountry: null,
        equityRegion: null,
        fixedIncomeCountry: {
          other: 17.866400000000002,
          hk: 2.9699,
          lu: 5.0235,
          bm: 0.6566,
          ua: 0.387,
          br: 1.768,
          id: 0.9655,
          sn: 2.1244,
          gb: 4.4354,
          ie: 2.4469,
          ca: 1.9396,
          us: 2.5413,
          il: 0.6789,
          ae: 1.78,
          in: 3.2517,
          kr: 0.3785,
          za: 1.9079,
          cl: 1.0321,
          cn: 5.6755,
          mx: 7.3626,
          my: 0.0662,
          co: 1.4905,
          es: 0.3622,
          ky: 9.2731,
          ar: 4.1157,
          at: 0.5012,
          pe: 1.5601,
          vn: 0.097,
          ng: 0.4662,
          nl: 8.56,
          tr: 9.2559
        },
        fixedIncomeRegion: {
          africaExNorthAfrica: 5.0182,
          asiaPacificExJapan: 5.0943,
          emergingMarketsAsia: 14.8461,
          emergingMarketsEurope: null,
          europeExUnitedKingdom: 17.7535,
          japan: null,
          latinAmerica: 19.4948,
          middleEastNorthAfrica: 4.7977,
          northAmericaExUnitedStates: 15.6342,
          other: 11.324499999999999,
          unitedKingdom: 4.4354,
          unitedStates: 2.5413,
          __typename: "RegionAllocation"
        },
        gicsSubIndustry: null,
        trbcIndustry: null,
        __typename: "FundAllocation"
      },
      apexSupport: null,
      assetStatus: "Active",
      benchmark: "Bloomberg Barclays Global High Yield TR",
      classification: "Global EM Hard Currency Bond",
      distributions: {
        capitalGain: {
          capitalGain: null,
          collectibles: null,
          longTermCapitalGain: null,
          mediumTermCapitalGain: null,
          nonQualifiedShortTermCapitalGain: null,
          qualifiedShortTermCapitalGain: null,
          returnOfCapital: null,
          shortTermCapitalGain: {
            accountingDate: null,
            exDate: "2012-12-27",
            exValue: 0.008,
            paymentDate: "2013-01-03",
            recordDate: null,
            reinvestmentDate: "2012-12-27",
            reinvestmentType: "Nav",
            reinvestmentValue: 26.67,
            taxableInterestIncome: null,
            __typename: "FundDistribution"
          },
          superLongTermCapitalGain: null,
          __typename: "CapitalGainDistributions"
        },
        foreignTaxCredit: null,
        income: {
          aggregateAccrual: null,
          exemptIncome: null,
          incomeDividend: {
            accountingDate: null,
            exDate: "2020-10-01",
            exValue: 0.108,
            paymentDate: "2020-10-07",
            recordDate: null,
            reinvestmentDate: "2020-10-01",
            reinvestmentType: "Nav",
            reinvestmentValue: 22.56657,
            taxableInterestIncome: null,
            __typename: "FundDistribution"
          },
          interestIncome: null,
          nonQualifiedIncomeDividend: {
            accountingDate: null,
            exDate: "2018-12-27",
            exValue: 0.1159,
            paymentDate: "2019-01-03",
            recordDate: null,
            reinvestmentDate: "2018-12-27",
            reinvestmentType: "Nav",
            reinvestmentValue: 22.36224,
            taxableInterestIncome: null,
            __typename: "FundDistribution"
          },
          qualifiedIncomeDividend: null,
          __typename: "IncomeDistributions"
        },
        repaymentCategory: null,
        __typename: "FundDistributions"
      },
      fees: {
        backLoad: null,
        frontLoad: null,
        fundExpenseRatio: 0.4,
        managementFee: 0.4,
        marketing12b1Fee: null,
        performanceFee: null,
        __typename: "Fees"
      },
      focus: {
        assetClassFocus: "Bond",
        geoFocus: "Global Emerging Markets",
        __typename: "Focus"
      },
      fundType: "Exchange Traded Funds",
      inceptionDate: "2012-05-08",
      institutional: false,
      managementCompany: "Van Eck Associates Corporation",
      midPrice: 22.57,
      netAssetValuePerShare: 22.45921,
      netAssets: 419825214.92,
      netAssetsDate: "2020-10-30",
      priceDate: "2020-11-02",
      regulatoryStructure: null,
      replicationStrategy: "Optimized",
      scores: {
        consistentReturn: {
          fiveYear: 5,
          overall: 5,
          tenYear: null,
          threeYear: 4,
          __typename: "Score"
        },
        expense: {
          fiveYear: 5,
          overall: 5,
          tenYear: null,
          threeYear: 5,
          __typename: "Score"
        },
        preservation: {
          fiveYear: 1,
          overall: 1,
          tenYear: null,
          threeYear: 1,
          __typename: "Score"
        },
        taxEfficiency: {
          fiveYear: 1,
          overall: 1,
          tenYear: null,
          threeYear: 1,
          __typename: "Score"
        },
        totalReturn: {
          fiveYear: 5,
          overall: 5,
          tenYear: null,
          threeYear: 4,
          __typename: "Score"
        },
        __typename: "Scores6"
      },
      tradeLotSize: 0,
      yields: {
        dailySecYield: 6.04,
        dailySecYieldDate: "2020-11-03",
        distributionYield: 6.2139318,
        dividendYield: null,
        lipperDistributionYield: 5.7418176,
        projectedYield: 5.6314599,
        secYield: 6.04,
        simpleYieldBegin: 5.7832558,
        simpleYieldEnd: 5.9921965,
        thirtyDayYield: 6.04,
        trailingTwelveMonthYield: 5.981503,
        __typename: "FundYields"
      },
      __typename: "Fund4"
    },
    id: "621e7f48-e332-4e92-a875-260ed4ec9569",
    identifiers: {
      apex: "92189F353",
      bbGlobal: null,
      cik: null,
      cins: null,
      cusip: "92189F353",
      isin: "US92189F3534",
      primaryTicker: null,
      refinitivAssetId: null,
      refinitivIssuePermId: null,
      refinitivLipperId: "40198207",
      refinitivLipperParentId: "36413687",
      refinitivLipperPermId: null,
      sedol: null,
      valoren: null,
      __typename: "Identifiers"
    },
    legalEntity: null,
    liquid: null,
    market: "USA",
    metadata: null,
    name: "VanEck Vectors Emg Mkts High Yield Bd ETF",
    price: 22.57,
    priceDate: "2020-11-02",
    priceQuotes: null,
    primaryExchange: "Arca",
    primaryExchangeMic: null,
    scores: {
      attractiveness: 1,
      credit: 3,
      efficiency: 3.4,
      liquidity: 3,
      risk: 7.330573492946154,
      timestamp: null,
      __typename: "RoverScores"
    },
    ticker: "HYEM",
    unit: null,
    universes: {
      custom: null,
      general: true,
      liquid: true,
      search: true,
      timestamp: "2020-11-03T05:28:39.394133Z",
      __typename: "Universes"
    },
    updatedAt: "2020-11-03T05:28:38.820932Z",
    updatedBy: "bry",
    __typename: "Asset5"
  },
  {
    allocation: {
      country: {
        other: 1.601,
        hk: 0.4401,
        ae: 0.4384,
        in: 0.1222,
        jp: 0.0972,
        kr: 0.5931,
        cl: 0.6042,
        it: 0.766,
        my: 0.1237,
        fr: 0.5166,
        sa: 0.1905,
        ky: 0.7909,
        qa: 0.2369,
        au: 0.7046,
        id: 0.1683,
        sn: 0.4718,
        gb: 3.2551,
        nl: 0.5255,
        ca: 3.6581,
        us: 85.1632
      },
      currency: { other: 2.4744, usd: 97.5255 },
      debtType: null,
      maturity: {
        fiveToTenYears: 15.923,
        greaterThanThirtyYears: 2.3415,
        lessThanOneYear: 23.6522,
        oneToThreeYears: 36.605,
        other: 3.204,
        tenToTwentyYears: 0.8937,
        threeToFiveYears: 2.0589,
        twentyToThirtyYears: 15.789,
        __typename: "MaturityAllocation"
      },
      rating: {
        a: 30.0911,
        aa: 6.9972,
        aaa: 33.7521,
        b: null,
        bb: null,
        bbb: 24.0456,
        c: null,
        cc: null,
        ccc: null,
        d: null,
        nr: 5.5812,
        __typename: "RatingAllocation2"
      },
      region: {
        africaExNorthAfrica: null,
        asiaPacificExJapan: 1.6165,
        emergingMarketsAsia: 1.0073,
        emergingMarketsEurope: null,
        europeExUnitedKingdom: 1.8081,
        japan: 0.0972,
        latinAmerica: 0.6042,
        middleEastNorthAfrica: 0.8659,
        northAmericaExUnitedStates: 5.6872,
        other: 2.8366,
        unitedKingdom: 3.2551,
        unitedStates: 82.222,
        __typename: "RegionAllocation"
      },
      sector: null,
      __typename: "Allocation7"
    },
    analytics: {
      convexity: null,
      creditBeta: null,
      currentYield: null,
      date: "2020-11-02",
      defaultAdjustedYield: null,
      distributionYield: 1.2455857,
      dividendYield: null,
      duration: null,
      effectiveDuration: null,
      gSpread: null,
      optionAdjustedSpread: null,
      recoveryRate: null,
      secYield: 1.4,
      source: "Lipper",
      spreadDuration: null,
      standaloneRisk: null,
      yearsToMaturity: null,
      yield: 1.4,
      yieldToCall: null,
      yieldToMaturity: null,
      yieldToWorst: null,
      zSpread: null,
      __typename: "Analytics"
    },
    assetSubtype: "EXCHANGE_TRADED_FUNDS",
    assetType: "FUND",
    bond: null,
    country: null,
    createdAt: "2019-11-22T09:54:38.244143Z",
    createdBy: null,
    currency: "USD",
    description:
      "The Fund seeks total return through a combination of current income and capital appreciation. The Fund invests primarily in a portfolio of investment grade debt instruments which normally maintain a weighted average portfolio duration of one year or less and a weighted average maturity of three years or less.",
    displayId: null,
    equity: null,
    fund: {
      allocation: {
        asset: {
          cash: -2.6599,
          equity: null,
          fixedIncome: 100.4674,
          other: 2.1926,
          __typename: "AssetAllocation"
        },
        currency: { other: 2.4744, usd: 97.5255 },
        equityCountry: null,
        equityRegion: null,
        fixedIncomeCountry: {
          other: 1.601,
          hk: 0.4401,
          ae: 0.4384,
          in: 0.1222,
          jp: 0.0972,
          kr: 0.5931,
          cl: 0.6042,
          it: 0.766,
          my: 0.1237,
          fr: 0.5166,
          sa: 0.1905,
          ky: 0.7909,
          qa: 0.2369,
          au: 0.7046,
          id: 0.1683,
          sn: 0.4718,
          gb: 3.2551,
          nl: 0.5255,
          ca: 3.6581,
          us: 85.1632
        },
        fixedIncomeRegion: {
          africaExNorthAfrica: null,
          asiaPacificExJapan: 1.6165,
          emergingMarketsAsia: 1.0073,
          emergingMarketsEurope: null,
          europeExUnitedKingdom: 1.8081,
          japan: 0.0972,
          latinAmerica: 0.6042,
          middleEastNorthAfrica: 0.8659,
          northAmericaExUnitedStates: 5.2182,
          other: 0.8317000000000001,
          unitedKingdom: 3.2551,
          unitedStates: 85.1632,
          __typename: "RegionAllocation"
        },
        gicsSubIndustry: null,
        trbcIndustry: null,
        __typename: "FundAllocation"
      },
      apexSupport: null,
      assetStatus: "Active",
      benchmark: "Bloomberg Barclays U.S. Aggregate Bond TR",
      classification: "Short Term",
      distributions: {
        capitalGain: null,
        foreignTaxCredit: null,
        income: {
          aggregateAccrual: null,
          exemptIncome: null,
          incomeDividend: {
            accountingDate: null,
            exDate: "2020-10-01",
            exValue: 0.05179,
            paymentDate: "2020-10-07",
            recordDate: null,
            reinvestmentDate: "2020-10-01",
            reinvestmentType: "Nav",
            reinvestmentValue: 49.8613,
            taxableInterestIncome: null,
            __typename: "FundDistribution"
          },
          interestIncome: null,
          nonQualifiedIncomeDividend: null,
          qualifiedIncomeDividend: null,
          __typename: "IncomeDistributions"
        },
        repaymentCategory: null,
        __typename: "FundDistributions"
      },
      fees: {
        backLoad: null,
        frontLoad: null,
        fundExpenseRatio: 0.15,
        managementFee: 0.15,
        marketing12b1Fee: null,
        performanceFee: null,
        __typename: "Fees"
      },
      focus: {
        assetClassFocus: "Bond",
        geoFocus: "United States of America",
        __typename: "Focus"
      },
      fundType: "Exchange Traded Funds",
      inceptionDate: "2018-04-05",
      institutional: false,
      managementCompany: "PGIM Investments LLC",
      midPrice: 49.84,
      netAssetValuePerShare: 49.8383,
      netAssets: 1092692755.2,
      netAssetsDate: "2020-10-30",
      priceDate: "2020-11-02",
      regulatoryStructure: null,
      replicationStrategy: null,
      scores: {
        consistentReturn: {
          fiveYear: null,
          overall: null,
          tenYear: null,
          threeYear: null,
          __typename: "Score"
        },
        expense: {
          fiveYear: null,
          overall: null,
          tenYear: null,
          threeYear: null,
          __typename: "Score"
        },
        preservation: {
          fiveYear: null,
          overall: null,
          tenYear: null,
          threeYear: null,
          __typename: "Score"
        },
        taxEfficiency: {
          fiveYear: null,
          overall: null,
          tenYear: null,
          threeYear: null,
          __typename: "Score"
        },
        totalReturn: {
          fiveYear: null,
          overall: null,
          tenYear: null,
          threeYear: null,
          __typename: "Score"
        },
        __typename: "Scores6"
      },
      tradeLotSize: 0,
      yields: {
        dailySecYield: 1.18,
        dailySecYieldDate: "2020-08-20",
        distributionYield: 1.4591188,
        dividendYield: null,
        lipperDistributionYield: 1.2455857,
        projectedYield: 2.0220047,
        secYield: 1.4,
        simpleYieldBegin: 1.9806778,
        simpleYieldEnd: 1.9889322,
        thirtyDayYield: 1.4,
        trailingTwelveMonthYield: 2.0642715,
        __typename: "FundYields"
      },
      __typename: "Fund4"
    },
    id: "d96cf090-a15d-40d0-82c0-03e6ccc0b154",
    identifiers: {
      apex: null,
      bbGlobal: null,
      cik: null,
      cins: null,
      cusip: "69344A107",
      isin: "US69344A1079",
      primaryTicker: null,
      refinitivAssetId: null,
      refinitivIssuePermId: null,
      refinitivLipperId: "40223647",
      refinitivLipperParentId: "36847334",
      refinitivLipperPermId: null,
      sedol: null,
      valoren: null,
      __typename: "Identifiers"
    },
    legalEntity: null,
    liquid: null,
    market: "USA",
    metadata: null,
    name: "PGIM Ultra Short Bond ETF",
    price: 49.84,
    priceDate: "2020-11-02",
    priceQuotes: null,
    primaryExchange: "Arca",
    primaryExchangeMic: null,
    scores: {
      attractiveness: 1.1963151855560177,
      credit: 3,
      efficiency: null,
      liquidity: 3,
      risk: 1.1702601596161422,
      timestamp: null,
      __typename: "RoverScores"
    },
    ticker: "PULS",
    unit: null,
    universes: {
      custom: null,
      general: true,
      liquid: true,
      search: true,
      timestamp: "2020-11-03T05:30:33.000727Z",
      __typename: "Universes"
    },
    updatedAt: "2020-11-03T05:30:32.957931Z",
    updatedBy: "bry",
    __typename: "Asset5"
  }
];
const server = setupServer();
describe("PortfolioDisplay", () => {
  beforeAll(() => server.listen());
  afterEach(() => client.clearStore());
  afterAll(() => server.close());
  xit("Should render external portfolio correctly", async () => {
    server.use(mockInpaasPortfolioRequests);
    render(
      <Route exact path="/portfolios/:type/:id">
        <PortfolioDisplay />
      </Route>,
      {
        route: "/portfolios/external/mock-portfolio-id"
      }
    );

    const invest = await screen.findByText(/invest now/i);
    userEvent.click(invest);
  });

  it("Should render with open orders", async () => {
    server.use(mockInpaasPortfolioRequests);
    render(
      <Route exact path="/portfolios/:type/:id">
        <PortfolioDisplay />
      </Route>,
      {
        route: `/portfolios/live/${mockYieldXPortfolio.getId()}`
      }
    );
    expect(() => screen.getByTestId("spinner")).toBeTruthy();
  });
});
